# Generated by Django 5.2.12 on 2026-04-07 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_observacao', models.DateField()),
                ('estadio_fenologico', models.CharField(max_length=50)),
                ('cultura', models.CharField(blank=True, max_length=100)),
                ('altura_planta_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('populacao_plantas', models.IntegerField(blank=True, null=True)),
                ('sanidade', models.CharField(blank=True, help_text='Ex: boa, média, ruim, presença de pragas/doenças', max_length=100)),
                ('umidade_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='talhoes.talhao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoramento',
                'verbose_name_plural': 'Monitoramentos',
                'db_table': 'monitoramentos',
                'ordering': ['-data_observacao'],
            },
        ),
    ]
