# Generated by Django 5.2.12 on 2026-04-07 03:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-data_observacao', '-created_at'], 'verbose_name': 'Monitoramento', 'verbose_name_plural': 'Monitoramentos'},
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='altura_planta_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='estadio_fenologico',
            field=models.CharField(choices=[('VE', 'VE - Emergência'), ('V1', 'V1 - 1 folha expandida'), ('V2', 'V2 - 2 folhas expandidas'), ('V3', 'V3 - 3 folhas expandidas'), ('V4', 'V4 - 4 folhas expandidas'), ('V5', 'V5 - 5 folhas expandidas'), ('V6', 'V6 - 6 folhas expandidas'), ('V7', 'V7 - 7 folhas expandidas'), ('V8', 'V8 - 8 folhas expandidas'), ('V9', 'V9 - 9 folhas expandidas'), ('V10', 'V10 - 10 folhas expandidas'), ('V11', 'V11 - 11 folhas expandidas'), ('V12', 'V12 - 12 folhas expandidas'), ('V13', 'V13 - 13 folhas expandidas'), ('V14', 'V14 - 14 folhas expandidas'), ('V15', 'V15 - 15 folhas expandidas'), ('V16', 'V16 - 16 folhas expandidas'), ('V17', 'V17 - 17 folhas expandidas'), ('V18', 'V18 - 18 folhas expandidas'), ('R1', 'R1 - Florescimento'), ('R2', 'R2 - Grão bolha'), ('R3', 'R3 - Grão leitoso'), ('R4', 'R4 - Grão pastoso'), ('R5', 'R5 - Grão dentado'), ('R6', 'R6 - Maturidade fisiológica')], max_length=3),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='populacao_plantas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='umidade_solo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual estimado de umidade do solo.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['data_observacao'], name='idx_monitor_data_obs'),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['estadio_fenologico'], name='idx_monitor_estadio'),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['ativa'], name='idx_monitor_ativa'),
        ),
    ]
