# Generated by Django 5.2.12 on 2026-04-07 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_monitoramento_options_and_more'),
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='exige_acao_imediata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='nivel_atencao',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='baixo', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='possui_anomalias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='resumo_diagnostico',
            field=models.TextField(blank=True, help_text='Resumo automático ou técnico do diagnóstico do monitoramento.'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='status_diagnostico',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('concluido', 'Concluído'), ('alerta', 'Alerta')], default='pendente', max_length=15),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['nivel_atencao'], name='idx_monitor_nivel_at'),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['status_diagnostico'], name='idx_monitor_status_diag'),
        ),
    ]
