# Generated by Django 5.2.12 on 2026-04-07 22:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_monitoramento_exige_acao_imediata_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='foto_monitoramento',
            field=models.ImageField(blank=True, help_text='Foto principal do monitoramento para futura análise visual por IA.', null=True, upload_to='monitoramentos/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ia_confianca_imagem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confiança percentual da IA na análise da imagem.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ia_erro_imagem',
            field=models.TextField(blank=True, help_text='Mensagem de erro do processamento da imagem, se houver.'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ia_estadio_fenologico_sugerido',
            field=models.CharField(blank=True, help_text='Estádio fenológico sugerido pela IA a partir da imagem.', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ia_observacoes_imagem',
            field=models.TextField(blank=True, help_text='Observações complementares da análise de imagem.'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ia_resultado_imagem',
            field=models.JSONField(blank=True, help_text='Resultado estruturado da análise visual da imagem.', null=True),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='imagem_processada_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora do último processamento da imagem.', null=True),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='status_imagem_ia',
            field=models.CharField(choices=[('nao_enviada', 'Não enviada'), ('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='nao_enviada', help_text='Status do processamento da imagem do monitoramento.', max_length=15),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['status_imagem_ia'], name='idx_monitor_status_img_ia'),
        ),
    ]
