# Generated by Django 5.2.12 on 2026-04-08 16:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_monitoramento_foto_monitoramento_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='faixa_risco',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('critico', 'Crítico')], default='baixo', help_text='Faixa qualitativa derivada do score de risco.', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='justificativa_risco',
            field=models.TextField(blank=True, help_text='Justificativa textual do score e da prioridade atribuída.'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='prioridade_operacional',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('imediata', 'Imediata')], default='baixa', help_text='Prioridade operacional para tratamento do monitoramento.', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='score_risco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score consolidado de risco agronômico de 0 a 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['score_risco'], name='idx_monitor_score_risco'),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['faixa_risco'], name='idx_monitor_faixa_risco'),
        ),
        migrations.AddIndex(
            model_name='monitoramento',
            index=models.Index(fields=['prioridade_operacional'], name='idx_monitor_prioridade_op'),
        ),
    ]
