# Generated by Django 5.2.12 on 2026-04-08 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_monitoramento_faixa_risco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='altura_planta_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura estimada da planta de milho em centímetros.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='cultura',
            field=models.CharField(blank=True, default='milho', help_text='Cultura de referência do monitoramento. Nesta fase oficial do projeto, o sistema opera exclusivamente com milho.', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='estadio_fenologico',
            field=models.CharField(choices=[('VE', 'VE - Emergência'), ('V1', 'V1 - 1 folha expandida'), ('V2', 'V2 - 2 folhas expandidas'), ('V3', 'V3 - 3 folhas expandidas'), ('V4', 'V4 - 4 folhas expandidas'), ('V5', 'V5 - 5 folhas expandidas'), ('V6', 'V6 - 6 folhas expandidas'), ('V7', 'V7 - 7 folhas expandidas'), ('V8', 'V8 - 8 folhas expandidas'), ('V9', 'V9 - 9 folhas expandidas'), ('V10', 'V10 - 10 folhas expandidas'), ('V11', 'V11 - 11 folhas expandidas'), ('V12', 'V12 - 12 folhas expandidas'), ('V13', 'V13 - 13 folhas expandidas'), ('V14', 'V14 - 14 folhas expandidas'), ('V15', 'V15 - 15 folhas expandidas'), ('V16', 'V16 - 16 folhas expandidas'), ('V17', 'V17 - 17 folhas expandidas'), ('V18', 'V18 - 18 folhas expandidas'), ('R1', 'R1 - Florescimento'), ('R2', 'R2 - Grão bolha'), ('R3', 'R3 - Grão leitoso'), ('R4', 'R4 - Grão pastoso'), ('R5', 'R5 - Grão dentado'), ('R6', 'R6 - Maturidade fisiológica')], help_text='Estádio fenológico observado no milho no momento da coleta.', max_length=3),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='foto_monitoramento',
            field=models.ImageField(blank=True, help_text='Foto principal do monitoramento para futura análise visual por IA, no contexto atual da cultura do milho.', null=True, upload_to='monitoramentos/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='ia_estadio_fenologico_sugerido',
            field=models.CharField(blank=True, help_text='Estádio fenológico do milho sugerido pela IA a partir da imagem.', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações livres do monitoramento de campo. Use para registrar a situação visível da lavoura de milho.'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='populacao_plantas',
            field=models.IntegerField(blank=True, help_text='Estimativa de população de plantas na área observada.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='sanidade',
            field=models.CharField(blank=True, help_text='Condição sanitária observada no milho. Ex.: boa, média, ruim, presença de pragas/doenças.', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='umidade_solo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual estimado de umidade do solo no ponto monitorado.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
