# Generated by Django 5.2.12 on 2026-04-06 22:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='area_total_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['nome'], name='idx_prop_nome'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['municipio'], name='idx_prop_municipio'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['uf'], name='idx_prop_uf'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['ativa'], name='idx_prop_ativa'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['created_at'], name='idx_prop_created_at'),
        ),
        migrations.AddConstraint(
            model_name='propriedade',
            constraint=models.CheckConstraint(condition=models.Q(('area_total_ha__gte', 0), ('area_total_ha__isnull', True), _connector='OR'), name='chk_prop_area_total_ha_gte_0'),
        ),
    ]
