# Generated by Django 5.2.12 on 2026-04-07 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('praga', 'Praga'), ('doenca', 'Doença'), ('deficiencia_nutricional', 'Deficiência Nutricional'), ('planta_nanica', 'Planta Nanica'), ('dano_climatico', 'Dano Climático'), ('planta_daninha', 'Planta Daninha'), ('outra', 'Outra')], max_length=50)),
                ('nome', models.CharField(help_text='Ex.: Lagarta-do-cartucho, deficiência de zinco, ferrugem etc.', max_length=150)),
                ('severidade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Baixa'), (2, '2 - Baixa'), (3, '3 - Média'), (4, '4 - Alta'), (5, '5 - Muito Alta')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('percentual_plantas_afetadas', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de plantas afetadas no ponto monitorado.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacao', models.TextField(blank=True)),
                ('exige_atencao', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='monitoramento.monitoramento')),
            ],
            options={
                'verbose_name': 'Anomalia',
                'verbose_name_plural': 'Anomalias',
                'db_table': 'anomalias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_anomalia_tipo'), models.Index(fields=['nome'], name='idx_anomalia_nome'), models.Index(fields=['severidade'], name='idx_anomalia_severidade'), models.Index(fields=['exige_atencao'], name='idx_anomalia_atencao')],
            },
        ),
    ]
