# Generated by Django 5.2.12 on 2026-04-10 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoramento', '0006_alter_monitoramento_altura_planta_cm_and_more'),
        ('propriedades', '0003_propriedade_poligono_alter_propriedade_area_total_ha_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo_agronomico', models.CharField(default='milho', help_text='Escopo agronômico oficial do alerta nesta fase: milho.', max_length=20)),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('risco', 'Risco'), ('clima', 'Clima'), ('sanidade', 'Sanidade'), ('umidade_solo', 'Umidade do solo'), ('imagem', 'Imagem'), ('operacional', 'Operacional'), ('anomalia', 'Anomalia')], default='operacional', max_length=20)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=10)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('imediata', 'Imediata')], default='baixa', max_length=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(help_text='Mensagem principal do alerta para exibição ao usuário.')),
                ('recomendacao', models.TextField(blank=True, help_text='Orientação operacional inicial associada ao alerta.')),
                ('regra_origem', models.CharField(blank=True, help_text='Identificador da regra que originou o alerta.', max_length=100)),
                ('dados_contexto', models.JSONField(blank=True, help_text='Dados estruturados usados para rastreabilidade do alerta.', null=True)),
                ('lido', models.BooleanField(default=False)),
                ('exige_confirmacao', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o alerta foi gerado.')),
                ('resolvido_em', models.DateTimeField(blank=True, help_text='Data/hora em que o alerta foi resolvido.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoramento.monitoramento')),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='propriedades.propriedade')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='talhoes.talhao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-gerado_em', '-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_alerta_tipo'), models.Index(fields=['severidade'], name='idx_alerta_severidade'), models.Index(fields=['prioridade'], name='idx_alerta_prioridade'), models.Index(fields=['status'], name='idx_alerta_status'), models.Index(fields=['ativa'], name='idx_alerta_ativa'), models.Index(fields=['lido'], name='idx_alerta_lido'), models.Index(fields=['gerado_em'], name='idx_alerta_gerado_em'), models.Index(fields=['escopo_agronomico'], name='idx_alerta_escopo_agronomico')],
            },
        ),
    ]
