# Generated by Django 5.2.12 on 2026-04-30 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('monitoramento', '0006_alter_monitoramento_altura_planta_cm_and_more'),
        ('propriedades', '0003_propriedade_poligono_alter_propriedade_area_total_ha_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o alerta foi resolvido, ignorado ou encerrado.', null=True),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['usuario', 'status', 'ativa'], name='idx_alerta_user_status'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['monitoramento', 'tipo', 'regra_origem'], name='idx_alerta_monitor_regra'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['talhao', 'status', 'ativa'], name='idx_alerta_talhao_status'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['propriedade', 'status', 'ativa'], name='idx_alerta_prop_status'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True), ('status__in', ['ativo', 'em_analise']), models.Q(('regra_origem', ''), _negated=True)), fields=('monitoramento', 'tipo', 'regra_origem'), name='uq_alerta_ativo_monitor_tipo_regra'),
        ),
    ]
