# Generated by Django 5.2.12 on 2026-04-07 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('artigo', 'Artigo'), ('manual', 'Manual'), ('boletim', 'Boletim'), ('legislacao', 'Legislação'), ('base_publica', 'Base Pública'), ('outro', 'Outro')], default='pdf', max_length=20)),
                ('categoria', models.CharField(choices=[('fenologia', 'Fenologia'), ('pragas', 'Pragas'), ('doencas', 'Doenças'), ('nutricao', 'Nutrição'), ('solo', 'Solo'), ('clima', 'Clima'), ('ndvi', 'NDVI'), ('manejo', 'Manejo'), ('geoprocessamento', 'Geoprocessamento'), ('geral', 'Geral')], default='geral', max_length=30)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='base_conhecimento/pdfs/')),
                ('url', models.URLField(blank=True)),
                ('conteudo_extraido', models.TextField(blank=True, help_text='Texto extraído do documento para futura indexação.')),
                ('palavras_chave', models.CharField(blank=True, help_text='Lista simples de palavras-chave separadas por vírgula.', max_length=500)),
                ('status_indexacao', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('indexado', 'Indexado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fontes_conhecimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte de Conhecimento',
                'verbose_name_plural': 'Base de Conhecimento',
                'db_table': 'fontes_conhecimento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_fonte_tipo'), models.Index(fields=['categoria'], name='idx_fonte_categoria'), models.Index(fields=['status_indexacao'], name='idx_fonte_indexacao'), models.Index(fields=['ativa'], name='idx_fonte_ativa'), models.Index(fields=['created_at'], name='idx_fonte_created')],
            },
        ),
    ]
