# Generated by Django 5.2.12 on 2026-04-08 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteconhecimento',
            name='escopo_cultura',
            field=models.CharField(choices=[('milho', 'Milho'), ('geral', 'Geral de apoio')], default='milho', help_text='Escopo agronômico da fonte. Nesta fase oficial do projeto, a base técnica ativa opera com foco em milho.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Arquivo técnico enviado para compor a base de conhecimento.', null=True, upload_to='base_conhecimento/pdfs/'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='conteudo_extraido',
            field=models.TextField(blank=True, help_text='Texto extraído do documento para indexação e busca semântica.'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['escopo_cultura'], name='idx_fonte_escopo_cultura'),
        ),
    ]
