# Generated by Django 5.2.12 on 2026-04-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0002_fonteconhecimento_escopo_cultura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteconhecimento',
            name='aplicacao_pratica',
            field=models.TextField(blank=True, help_text='Explica como a informação pode ser aplicada no monitoramento agrícola, diagnóstico, interpretação de campo ou tomada de decisão.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='fonte_oficial',
            field=models.BooleanField(default=False, help_text='Indica se a fonte pertence a órgão oficial, instituição técnica ou base pública confiável.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='limitacoes_uso',
            field=models.TextField(blank=True, help_text='Registra limitações, cuidados de interpretação ou restrições de uso da fonte técnica.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='mensagem_indexacao',
            field=models.TextField(blank=True, help_text='Mensagem técnica sobre o status de indexação, erro ou necessidade de revisão.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='nivel_confiabilidade',
            field=models.CharField(choices=[('oficial', 'Fonte oficial'), ('tecnica', 'Fonte técnica reconhecida'), ('academica', 'Fonte acadêmica'), ('apoio', 'Fonte de apoio'), ('nao_classificada', 'Não classificada')], default='nao_classificada', help_text='Classificação da confiabilidade da fonte para uso técnico, IA e relatórios.', max_length=30),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='recomendada_para_ia',
            field=models.BooleanField(default=False, help_text='Indica se a fonte pode ser usada como apoio em diagnósticos por IA e geração de relatórios técnicos.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='recomendada_para_relatorio',
            field=models.BooleanField(default=False, help_text='Indica se a fonte pode ser citada ou usada como base de apoio em relatórios.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='resumo_tecnico',
            field=models.TextField(blank=True, help_text='Resumo técnico validado da fonte. Campo recomendado para consulta rápida, relatórios e apoio diagnóstico.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='status_revisao',
            field=models.CharField(choices=[('nao_revisado', 'Não revisado'), ('em_revisao', 'Em revisão'), ('revisado', 'Revisado'), ('aprovado', 'Aprovado para uso técnico'), ('reprovado', 'Reprovado')], default='nao_revisado', help_text='Status de revisão humana/técnica da fonte antes de uso em diagnóstico.', max_length=30),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='topicos_tecnicos',
            field=models.CharField(blank=True, help_text='Tópicos técnicos principais separados por vírgula. Exemplo: V4, V6, estresse hídrico, lagarta-do-cartucho, NDVI.', max_length=700),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de publicação ou referência do material técnico.', null=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a fonte está ativa para consulta no sistema.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='autor',
            field=models.CharField(blank=True, help_text='Autor, pesquisador, órgão ou responsável técnico pelo conteúdo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='categoria',
            field=models.CharField(choices=[('fenologia', 'Fenologia'), ('pragas', 'Pragas'), ('doencas', 'Doenças'), ('nutricao', 'Nutrição'), ('solo', 'Solo'), ('clima', 'Clima'), ('irrigacao', 'Irrigação'), ('manejo', 'Manejo'), ('plantio', 'Plantio'), ('colheita', 'Colheita'), ('produtividade', 'Produtividade'), ('sensoriamento_remoto', 'Sensoriamento Remoto'), ('ndvi', 'NDVI'), ('geoprocessamento', 'Geoprocessamento'), ('qgis', 'QGIS'), ('diagnostico', 'Diagnóstico Agronômico'), ('geral', 'Geral')], default='geral', max_length=40),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='conteudo_extraido',
            field=models.TextField(blank=True, help_text='Texto extraído do documento para indexação, busca e apoio futuro à IA.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição geral da fonte técnica cadastrada.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='instituicao',
            field=models.CharField(blank=True, help_text='Instituição associada à fonte, como Embrapa, Fundação MT, Senai, universidade etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações administrativas ou técnicas sobre a fonte.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Lista simples de palavras-chave separadas por vírgula.', max_length=700),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='status_indexacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('indexado', 'Indexado'), ('revisar', 'Revisar'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('artigo', 'Artigo'), ('manual', 'Manual'), ('boletim', 'Boletim Técnico'), ('cartilha', 'Cartilha'), ('nota_tecnica', 'Nota Técnica'), ('livro', 'Livro'), ('legislacao', 'Legislação'), ('base_publica', 'Base Pública'), ('qgis', 'Material QGIS / Geoprocessamento'), ('outro', 'Outro')], default='pdf', max_length=30),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='titulo',
            field=models.CharField(help_text='Título principal da fonte técnica.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='url',
            field=models.URLField(blank=True, help_text='Link da fonte técnica, quando o conteúdo estiver disponível online.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pelo cadastro da fonte técnica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fontes_conhecimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['nivel_confiabilidade'], name='idx_fonte_confiabilidade'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['status_revisao'], name='idx_fonte_revisao'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['recomendada_para_ia'], name='idx_fonte_ia'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['recomendada_para_relatorio'], name='idx_fonte_relatorio'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['fonte_oficial'], name='idx_fonte_oficial'),
        ),
    ]
