# Generated by Django 5.2.12 on 2026-04-22 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0003_fonteconhecimento_aplicacao_pratica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fonteconhecimento',
            name='idx_fonte_confiabilidade',
        ),
        migrations.RemoveIndex(
            model_name='fonteconhecimento',
            name='idx_fonte_revisao',
        ),
        migrations.RemoveIndex(
            model_name='fonteconhecimento',
            name='idx_fonte_ia',
        ),
        migrations.RemoveIndex(
            model_name='fonteconhecimento',
            name='idx_fonte_relatorio',
        ),
        migrations.RemoveIndex(
            model_name='fonteconhecimento',
            name='idx_fonte_oficial',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='fonte_oficial',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='limitacoes_uso',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='mensagem_indexacao',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='nivel_confiabilidade',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='recomendada_para_ia',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='recomendada_para_relatorio',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='resumo_tecnico',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='status_revisao',
        ),
        migrations.RemoveField(
            model_name='fonteconhecimento',
            name='topicos_tecnicos',
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='confiabilidade',
            field=models.PositiveSmallIntegerField(default=3, help_text='Nível simples de confiabilidade da fonte, de 1 a 5. Use 5 para fontes técnicas oficiais, instituições reconhecidas ou materiais validados.'),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_conhecimento_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fonteconhecimento',
            name='status_curadoria',
            field=models.CharField(choices=[('em_revisao', 'Em revisão'), ('aprovado', 'Aprovado'), ('arquivado', 'Arquivado'), ('erro', 'Com erro')], default='em_revisao', help_text='Status de curadoria da fonte para uso em IA, diagnósticos e relatórios.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='aplicacao_pratica',
            field=models.TextField(blank=True, help_text='Descrição objetiva de como esta fonte pode apoiar diagnósticos, relatórios, recomendações ou análise técnica no EspIAgro.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='categoria',
            field=models.CharField(choices=[('fenologia', 'Fenologia'), ('pragas', 'Pragas'), ('doencas', 'Doenças'), ('nutricao', 'Nutrição'), ('solo', 'Solo'), ('clima', 'Clima'), ('ndvi', 'NDVI'), ('manejo', 'Manejo'), ('geoprocessamento', 'Geoprocessamento'), ('geral', 'Geral')], default='geral', max_length=30),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='conteudo_extraido',
            field=models.TextField(blank=True, help_text='Texto extraído do documento para indexação e busca técnica.'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='instituicao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Lista simples de palavras-chave separadas por vírgula.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='status_indexacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('indexado', 'Indexado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('artigo', 'Artigo'), ('manual', 'Manual'), ('boletim', 'Boletim'), ('legislacao', 'Legislação'), ('base_publica', 'Base Pública'), ('outro', 'Outro')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fontes_conhecimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['status_curadoria'], name='idx_fonte_curadoria'),
        ),
        migrations.AddIndex(
            model_name='fonteconhecimento',
            index=models.Index(fields=['confiabilidade'], name='idx_fonte_confiabilidade'),
        ),
    ]
