# Generated by Django 5.2.12 on 2026-04-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoramento', '0003_monitoramento_exige_acao_imediata_and_more'),
        ('propriedades', '0002_alter_propriedade_area_total_ha_and_more'),
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('monitoramento', 'Monitoramento'), ('talhao', 'Talhão'), ('propriedade', 'Propriedade'), ('geral', 'Geral')], default='monitoramento', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True)),
                ('conteudo_json', models.JSONField(blank=True, help_text='Estrutura consolidada do relatório para renderização futura.', null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL do PDF gerado futuramente.')),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerado_em', models.DateTimeField(blank=True, help_text='Data/hora em que o relatório foi efetivamente gerado.', null=True)),
                ('monitoramento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='monitoramento.monitoramento')),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='propriedades.propriedade')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='talhoes.talhao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'relatorios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_relatorio_tipo'), models.Index(fields=['status'], name='idx_relatorio_status'), models.Index(fields=['ativa'], name='idx_relatorio_ativa'), models.Index(fields=['created_at'], name='idx_relatorio_created')],
            },
        ),
    ]
