# Generated by Django 5.2.12 on 2026-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0001_initial'),
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='referencias_tecnicas',
            field=models.ManyToManyField(blank=True, help_text='Fontes técnicas vinculadas ao relatório para rastreabilidade.', related_name='relatorios', to='base_conhecimento.fonteconhecimento'),
        ),
    ]
