# Generated by Django 5.2.12 on 2026-04-07 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0001_initial'),
        ('monitoramento', '0003_monitoramento_exige_acao_imediata_and_more'),
        ('propriedades', '0002_alter_propriedade_area_total_ha_and_more'),
        ('relatorios', '0002_relatorio_referencias_tecnicas'),
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='ia_erro',
            field=models.TextField(blank=True, help_text='Mensagem de erro da IA, se houver.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_fontes_utilizadas',
            field=models.JSONField(blank=True, help_text='Lista de fontes técnicas efetivamente citadas pela IA.', null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_gerado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o diagnóstico por IA foi processado.', null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_interpretacao_agronomica',
            field=models.TextField(blank=True, help_text='Interpretação agronômica estruturada gerada pela IA.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_limitacoes',
            field=models.TextField(blank=True, help_text='Limitações declaradas pela IA para o diagnóstico.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_modelo',
            field=models.CharField(blank=True, help_text='Modelo de IA utilizado na geração do diagnóstico.', max_length=100),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_modo_geracao',
            field=models.CharField(blank=True, help_text='Modo de geração do apoio diagnóstico, ex: regras, ia_local + regras.', max_length=50),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_pontos_atencao',
            field=models.JSONField(blank=True, help_text='Lista estruturada de pontos de atenção do diagnóstico.', null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_recomendacoes',
            field=models.JSONField(blank=True, help_text='Lista estruturada de recomendações iniciais geradas pela IA.', null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_resposta_completa',
            field=models.TextField(blank=True, help_text='Texto completo retornado pela IA.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_resumo_tecnico',
            field=models.TextField(blank=True, help_text='Resumo técnico principal do diagnóstico.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='ia_status',
            field=models.CharField(choices=[('nao_utilizada', 'Não utilizada'), ('fallback', 'Fallback'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='nao_utilizada', help_text='Status do uso de IA na geração do relatório.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['ia_status'], name='idx_relatorio_ia_status'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['ia_gerado_em'], name='idx_relatorio_ia_gerado_em'),
        ),
    ]
