# Generated by Django 5.2.12 on 2026-04-08 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0001_initial'),
        ('monitoramento', '0005_monitoramento_faixa_risco_and_more'),
        ('propriedades', '0003_propriedade_poligono_alter_propriedade_area_total_ha_and_more'),
        ('relatorios', '0003_relatorio_ia_erro_relatorio_ia_fontes_utilizadas_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='faixa_risco',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('critico', 'Crítico')], help_text='Faixa de risco consolidada do relatório.', max_length=20),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='justificativa_risco',
            field=models.TextField(blank=True, help_text='Justificativa consolidada do risco do relatório.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='prioridade_operacional',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('imediata', 'Imediata')], help_text='Prioridade operacional consolidada do relatório.', max_length=20),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='risco_gerado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que os campos estruturados de risco foram consolidados no relatório.', null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='score_risco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de risco consolidado do relatório.', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['faixa_risco'], name='idx_relatorio_faixa_risco'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['prioridade_operacional'], name='idx_relatorio_prioridade_op'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['risco_gerado_em'], name='idx_relatorio_risco_gerado'),
        ),
    ]
