# Generated by Django 5.2.12 on 2026-04-08 22:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0002_fonteconhecimento_escopo_cultura_and_more'),
        ('monitoramento', '0006_alter_monitoramento_altura_planta_cm_and_more'),
        ('propriedades', '0003_propriedade_poligono_alter_propriedade_area_total_ha_and_more'),
        ('relatorios', '0004_relatorio_faixa_risco_relatorio_justificativa_risco_and_more'),
        ('talhoes', '0003_talhao_poligono_alter_talhao_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='score_risco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de risco consolidado do relatório.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['score_risco'], name='idx_relatorio_score_risco'),
        ),
    ]
