# Generated by Django 5.2.12 on 2026-04-06 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cultivar', models.CharField(blank=True, max_length=150)),
                ('sistema_cultivo', models.CharField(blank=True, max_length=100)),
                ('data_plantio', models.DateField(blank=True, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='propriedades.propriedade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'db_table': 'talhoes',
                'ordering': ['nome'],
            },
        ),
    ]
