# Generated by Django 5.2.12 on 2026-04-06 22:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_alter_propriedade_area_total_ha_and_more'),
        ('talhoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['nome'], name='idx_talhao_nome'),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['propriedade'], name='idx_talhao_propriedade'),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['cultivar'], name='idx_talhao_cultivar'),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['sistema_cultivo'], name='idx_talhao_sist_cult'),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['ativa'], name='idx_talhao_ativa'),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['created_at'], name='idx_talhao_created_at'),
        ),
        migrations.AddConstraint(
            model_name='talhao',
            constraint=models.CheckConstraint(condition=models.Q(('area_ha__gte', 0), ('area_ha__isnull', True), _connector='OR'), name='chk_talhao_area_ha_gte_0'),
        ),
    ]
