# Generated by Django 5.2.12 on 2026-04-07 21:50

import django.contrib.gis.db.models.fields
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_alter_propriedade_area_total_ha_and_more'),
        ('talhoes', '0002_alter_talhao_area_ha_talhao_idx_talhao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Geometria geográfica do talhão em WGS84 (GeoJSON/Polygon).', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área informada manualmente pelo usuário em hectares.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='talhao',
            index=models.Index(fields=['propriedade', 'ativa'], name='idx_talhao_prop_ativa'),
        ),
    ]
